### ISSUE TITLE
Cannot get role to work with v2.10.0

### ISSUE THREAD

**Issue by renesas-brandon-hussey** [sdarwin/Ansible-VNC#8]
I recently updated Ansible to v2.10.0 on my Ubuntu 18.04 controller box. I cannot get the role to work since updating. Here's what I've found through some digging.

It always fails here:
```
TASK [sdarwin.vnc : install desktop packages] ******************************************************************************************
fatal: [***]: FAILED! => {"msg": "'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'xfce4'"}
```

It appears that the issue is with this:

```
- name: set facts based on defaults
  set_fact:
    "{{ item[8:] }}": "{{  vars[item[8:]] | default(vars[item]) }}"
  when: item is match("^default_")
  with_items:
    "{{ vars | list }}"
```

It looks like in previous versions of Ansible, this created a new hash (or dictionary? I don't really know) object. Now it seems to create an AnsibleUnsafeText object which cannot be queried. I checked the type and saw this:

```
- name: dbg
  debug:
    msg: "{{ vnc_desktop_packages | type_debug }}"
```

Output:

```
TASK [sdarwin.vnc : dbg] ***************************************************************************************************************
ok: [***] => {
    "msg": "AnsibleUnsafeText"
}
```

Another debug task:

```
- name: dbg
  debug:
    msg: "{{ vnc_desktop_packages }}"
```

and this is what is output:

```
ok: [***] => {
    "msg": "AnsibleMapping([('gnome', ['ubuntu-desktop', 'gnome-panel', 'gnome-settings-daemon', 'metacity', 'nautilus', 'gnome-terminal', 'xterm']), ('xfce4', ['xfce4', 'gnome-icon-theme', 'gnome-terminal', 'firefox', 'xterm'])])"
}
```

The data is there, it's just not in an object that Ansible is allowing the job to access.

**Comment by renesas-brandon-hussey** [comment]
Sorry for creating a duplicate. GitHub gave me a 404 error after submitting the first ticket and I did not think it went through.
